spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: moon
    url: jdbc:mysql:///weixin_shop?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true